models:
  csym:
    num_texture_types: 4
    parameters:
      num_points: 250
      radius_offset: 0.7
      radius: [30, 50]
      height: [80, 100]
      phi_amplitude: [0, 0.3]
      phi_frequency: [0, 100]
      phi_duty_cycle: [0, 1]
      z_amplitude: [0, 0.1]
      z_frequency: [0, 10]
      z_duty_cycle: [0, 1]
      twist: [-2, 2]
      edginess: [-2, 5]
      tilt_x: [-200, 200]
      tilt_y: [-200, 200]

  rsym:
    num_texture_types: 4
    parameters:
      num_points: 250
      r_ratio: [0, 1]
      x_scaler: [1, 3]
      y_scaler: [1, 3]
      z_scaler: [1, 4]
      phi_amplitude: [0, 1]
      phi_frequency: [0, 20]
      phi_duty_cycle: [0, 1]
      theta_amplitude: [0, 1]
      theta_frequency: [0, 20]
      theta_duty_cycle: [0, 1]
      e1_twist: [-2, 2]
      e2_twist: [-2, 2]
      e3_twist: [-2, 2]
      edginess: [0, 10]
      tilt_x: [-200, 200]
      tilt_y: [-200, 200]
      
app:
  host: 0.0.0.0
  port: 8000
  figure: 
    height: 600
    margin:
      t: 0
      b: 0
      l: 0
      r: 0
    color: '#00b3c7'
    lighting: 
      ambient: 0.1
      diffuse: 1
      fresnel: .1
      specular: 0.2
      roughness: .1
      facenormalsepsilon: 0
    lightposition: 
      x: 500
      y: 500
      z: 500
  dropdown: 
  text: 