name: leo
channels:
  - defaults
dependencies:
  - python=3.9.13
  - pip:
    - dash==2.0.0
    - dash-bootstrap-components==1.0.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask-compress==1.13
    - gunicorn==20.1.0
    - joblib==1.3.2
    - matplotlib==3.4.3
    - numpy==1.20.3
    - numpy-stl==2.16.3
    - plotly==5.1.0
    - python-utils==3.5.2
    - pyyaml==5.4.1
    - scikit-learn==1.3.0
    - scipy==1.7.1
    - werkzeug==2.0.3

